# Sacristy L1 Testnet CL Genesis Configuration

# Centrally-configured settings.
SECONDS_PER_SLOT: $SLOT_DURATION_IN_SECONDS

# Reasonable merged-at-genesis testing settings.
PRESET_BASE: '$PRESET_BASE'
CONFIG_NAME: 'sacristy'
GENESIS_DELAY: $GENESIS_DELAY
MIN_GENESIS_TIME: $GENESIS_TIMESTAMP
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: $NUMBER_OF_VALIDATORS
GENESIS_FORK_VERSION: $GENESIS_FORK_VERSION
SECONDS_PER_ETH1_BLOCK: $SECONDS_PER_ETH1_BLOCK
ETH1_FOLLOW_DISTANCE: $ETH1_FOLLOW_DISTANCE
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: $MIN_VALIDATOR_WITHDRAWABILITY_DELAY
SHARD_COMMITTEE_PERIOD: $SHARD_COMMITTEE_PERIOD
TERMINAL_TOTAL_DIFFICULTY: $TERMINAL_TOTAL_DIFFICULTY
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615
MAX_PAYLOAD_SIZE: $MAX_PAYLOAD_SIZE
MAX_REQUEST_BLOCKS_DENEB: $MAX_REQUEST_BLOCKS_DENEB

# Staking settings.
DEPOSIT_CHAIN_ID: $CHAIN_ID
DEPOSIT_NETWORK_ID: $CHAIN_ID
DEPOSIT_CONTRACT_ADDRESS: $DEPOSIT_CONTRACT_ADDRESS
EJECTION_BALANCE: $EJECTION_BALANCE
CHURN_LIMIT_QUOTIENT: $CHURN_LIMIT_QUOTIENT
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: $MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT

# All current forks active and future forks disabled.
ALTAIR_FORK_VERSION: $ALTAIR_FORK_VERSION
ALTAIR_FORK_EPOCH: $ALTAIR_FORK_EPOCH
BELLATRIX_FORK_VERSION: $BELLATRIX_FORK_VERSION
BELLATRIX_FORK_EPOCH: $BELLATRIX_FORK_EPOCH
CAPELLA_FORK_VERSION: $CAPELLA_FORK_VERSION
CAPELLA_FORK_EPOCH: $CAPELLA_FORK_EPOCH
DENEB_FORK_VERSION: $DENEB_FORK_VERSION
DENEB_FORK_EPOCH: $DENEB_FORK_EPOCH
ELECTRA_FORK_VERSION: $ELECTRA_FORK_VERSION
ELECTRA_FORK_EPOCH: $ELECTRA_FORK_EPOCH
FULU_FORK_VERSION: $FULU_FORK_VERSION
FULU_FORK_EPOCH: $FULU_FORK_EPOCH
GLOAS_FORK_VERSION: $GLOAS_FORK_VERSION
GLOAS_FORK_EPOCH: $GLOAS_FORK_EPOCH
EIP7441_FORK_VERSION: $EIP7441_FORK_VERSION
EIP7441_FORK_EPOCH: $EIP7441_FORK_EPOCH
EIP7805_FORK_VERSION: $EIP7805_FORK_VERSION
EIP7805_FORK_EPOCH: $EIP7805_FORK_EPOCH

# Blob and PeerDAS parameters.
MAX_BLOBS_PER_BLOCK_ELECTRA: $MAX_BLOBS_PER_BLOCK_ELECTRA
MAX_REQUEST_BLOB_SIDECARS_ELECTRA: $MAX_REQUEST_BLOB_SIDECARS_ELECTRA
DATA_COLUMN_SIDECAR_SUBNET_COUNT: $DATA_COLUMN_SIDECAR_SUBNET_COUNT
SAMPLES_PER_SLOT: $SAMPLES_PER_SLOT
CUSTODY_REQUIREMENT: $CUSTODY_REQUIREMENT
MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS: $MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS
BLOB_SCHEDULE: []
